import type { Metadata } from "next";

import { ScrollToTopButton } from "@/components/ScrollToTopButton";
import { CartWidget } from "@/components/CartWidget";
import { Navbar } from "@/components/Navbar";

import { CartProvider } from "@/context/CartContext";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-gray-50">
        <CartProvider>
          <Navbar />
          {children}
          <ScrollToTopButton />
          <CartWidget />
        </CartProvider>
      </body>
    </html>
  );
}
